CREATE DATABASE ECOMMERCE_DB
GO

USE ECOMMERCE_DB
GO

CREATE TABLE ROLES(
	Id TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Rol VARCHAR(50) NOT NULL
)
GO

CREATE TABLE USUARIOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Usuario VARCHAR(50) NOT NULL UNIQUE,
	Clave VARCHAR(255) NOT NULL,
	IdRol TINYINT NOT NULL FOREIGN KEY REFERENCES ROLES(Id)
)
GO

CREATE TABLE CLIENTES(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Telefono VARCHAR(15) NULL,
	IdUsuario INTEGER NOT NULL FOREIGN KEY REFERENCES USUARIOS(Id) UNIQUE
)
GO

CREATE TABLE DIRECCIONES(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdCliente INTEGER NOT NULL FOREIGN KEY REFERENCES CLIENTES(Id),
	Calle VARCHAR(50) NOT NULL,
	Numero INTEGER NOT NULL,
	Localidad VARCHAR(50) NOT NULL,
	CodigoPostal VARCHAR(20) NOT NULL,
	Observaciones VARCHAR(150) NULL
)
GO

CREATE TABLE CARRITOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Fecha DATETIME NOT NULL,
	Precio DECIMAL(18,2) NOT NULL,
	IdCliente INTEGER NOT NULL FOREIGN KEY REFERENCES CLIENTES(Id)
)
GO

CREATE TABLE CATEGORIAS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Descripcion VARCHAR(255) NOT NULL
)
GO

CREATE TABLE MARCAS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(70) NOT NULL,
)
GO


CREATE TABLE PRODUCTOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Sku VARCHAR(70) NOT NULL UNIQUE,
	IdCategoria INTEGER NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(Id),
	IdMarca INTEGER NOT NULL FOREIGN KEY REFERENCES MARCAS(Id),
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(255) NULL,
	Precio DECIMAL NOT NULL,
	Costo DECIMAL(18,2) NULL,
	Stock INTEGER NULL CHECK (Stock >= 0),
	Estado BIT NOT NULL
)
GO

CREATE TABLE IMAGENES(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Url VARCHAR(255) NOT NULL,
	IdProducto INTEGER NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(Id)
)
GO

CREATE TABLE ITEM_CARRITOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdCarrito INTEGER NOT NULL FOREIGN KEY REFERENCES CARRITOS(Id),
	IdProducto INTEGER NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(Id),
	Cantidad SMALLINT NOT NULL CHECK (Cantidad >= 0),
	Precio DECIMAL(18,2) NOT NULL
)
GO

CREATE TABLE METODOS_DE_PAGO(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL
)
GO

CREATE TABLE FORMAS_DE_ENTREGA(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL
)
GO

CREATE TABLE ESTADOS_DE_PEDIDO(
	Id TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Estado VARCHAR(50) NOT NULL
)
GO

CREATE TABLE PEDIDOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdCliente INTEGER NOT NULL FOREIGN KEY REFERENCES CLIENTES(Id),
	IdDireccion INTEGER NOT NULL FOREIGN KEY REFERENCES DIRECCIONES(Id),
	IdMetodoDePago INTEGER NOT NULL FOREIGN KEY REFERENCES METODOS_DE_PAGO(Id),
	Fecha DATETIME NOT NULL,
	Precio DECIMAL(18,2) NOT NULL,
	IdFormaDeEntrega INTEGER NOT NULL FOREIGN KEY REFERENCES FORMAS_DE_ENTREGA(Id),
	IdEstado TINYINT NOT NULL FOREIGN KEY REFERENCES ESTADOS_DE_PEDIDO(Id)
)
GO

CREATE TABLE OBSERVACIONES_PEDIDOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdPedido INTEGER NOT NULL FOREIGN KEY REFERENCES PEDIDOS(Id),
	Observacion VARCHAR(255)
)
GO

CREATE TABLE ITEM_PEDIDOS(
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdPedido INTEGER NOT NULL FOREIGN KEY REFERENCES PEDIDOS(Id),
	IdProducto INTEGER NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(Id),
	Cantidad SMALLINT NOT NULL CHECK (Cantidad >= 0),
	Precio DECIMAL(18,2) NOT NULL
)
GO
